version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.9.4
    steps:
    - checkout
    - run:
        command: npm install
    #save Cache
    -save_cache:
        paths:
          - node_modules
        key: v1-node-modules-cache-{{ checksum "package.json" }}
    - run:
        name: Build project
        command: npm run build
  UnitTest:
    docker:
    - image: circleci/node:8.9.4
    steps:
    - checkout
    - restore_cache:
        key: v1-node-modules-cache-{{ checksum "package.json" }}
    - run:
        name: install Deps
        command: npm install
    - run:
        command: npm run test:unit
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - UnitTest:
      requires:
       - build
